services:
  mongo:
    image: mongo:7
    container_name: portfolio_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - portfolio_net

  backend:
    build: ./backend
    container_name: portfolio_backend
    restart: unless-stopped
    env_file: ./backend/.env
    depends_on:
      - mongo
    volumes:
      - uploads_data:/app/uploads
    networks:
      - portfolio_net

  frontend:
    build: ./frontend
    container_name: portfolio_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio_net

volumes:
  mongo_data:
  uploads_data:

networks:
  portfolio_net:
    driver: bridge
