services:

  mongo:
    image: mongo:7
    container_name: portfolio_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - portfolio_net

  backend:
    build: ./backend
    container_name: portfolio_backend
    restart: unless-stopped
    env_file: ./backend/.env
    depends_on:
      - mongo
    volumes:
      - uploads_data:/app/uploads
    networks:
      - portfolio_net

  frontend:
    build: ./frontend
    container_name: portfolio_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio_net

  sonarqube:
    image: sonarqube:community
    container_name: portfolio_sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
      - sonar_extensions:/opt/sonarqube/extensions
    networks:
      - portfolio_net

volumes:
  mongo_data:
  uploads_data:
  sonar_data:
  sonar_logs:
  sonar_extensions:

networks:
  portfolio_net:
    driver: bridge
