# Identifiant unique du projet (doit correspondre à la project key SonarQube)
sonar.projectKey=portfolio-fullstack
sonar.projectName=Portfolio Fullstack
sonar.projectVersion=1.0

# Dossiers à analyser
sonar.sources=frontend/src,backend

# Dossiers à exclure de l'analyse
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/uploads/**

# Encodage
sonar.sourceEncoding=UTF-8

# URL du serveur SonarQube
sonar.host.url=http://172.16.64.131:9000
